/**
 * test_superadmin_governance_ui.js
 *
 * Comprehensive Automated Verification Suite for SuperAdmin Governance UI:
 * 1. Navigation verification (menuConfigs.js contains Today's Tasks, WhatsApp Engine, Communication Desk, Monitoring, Trash)
 * 2. AdminTaskDismissal Model creation and indexing
 * 3. Task Dismissal API (POST /api/admin/tasks/completed/:id/dismiss)
 * 4. Dismissed tasks filtered from Today's Tasks completed list
 * 5. Non-deletion assertion: Communication & AuditLog records are preserved
 * 6. Admin Profile 2FA toggle persistence (PUT /api/admin/profile/update)
 * 7. Admin Login History creation & stable ID removal (DELETE /api/admin/profile/login-history/:id)
 * 8. Protection against removing current active session from login history
 * 9. Safe System Settings (GET /api/admin/settings hides jwtSecret/secrets)
 * 10. System Settings persistence in MongoDB (PUT /api/admin/settings persists safe fields)
 * 11. Backup metadata/intent recording (POST /api/admin/backup & GET /api/admin/backups)
 * 12. MessageDetailDrawer dark theme / contrast validation
 */

"use strict";

const mongoose = require("mongoose");
const path = require("path");
const fs = require("fs");
require("dotenv").config({ path: path.join(__dirname, "../.env") });

const Admin = require("../models/Admin");
const Communication = require("../models/Communication");
const AuditLog = require("../models/AuditLog");
const SystemSetting = require("../models/SystemSetting");
const Backup = require("../models/Backup");
const AdminTaskDismissal = require("../models/AdminTaskDismissal");

let testAdmin = null;
let testAdminToken = null;

async function runTests() {
  console.log("\n=======================================================");
  console.log("  HOSTELMATE ENTERPRISE — SUPERADMIN GOVERNANCE TEST SUITE");
  console.log("=======================================================\n");

  const mongoUri = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/hostelmate_test";
  await mongoose.connect(mongoUri);
  console.log("✓ Connected to MongoDB for test run\n");

  let passed = 0;
  let failed = 0;

  function assert(condition, message) {
    if (condition) {
      console.log(`  ✓ PASS: ${message}`);
      passed++;
    } else {
      console.error(`  ✗ FAIL: ${message}`);
      failed++;
    }
  }

  try {
    // -------------------------------------------------------------
    // TEST 1: Navigation Configuration Audit
    // -------------------------------------------------------------
    console.log("[1/10] Verifying SuperAdmin Navigation Menu Configs...");
    const menuConfigsPath = path.join(__dirname, "../../Frontend/src/design-system/layouts/menuConfigs.js");
    const menuConfigsContent = fs.readFileSync(menuConfigsPath, "utf8");

    assert(menuConfigsContent.includes("key: 'tasks'"), "Today's Tasks (/admin/tasks) is present in live adminMenuItems");
    assert(menuConfigsContent.includes("key: 'whatsapp'"), "WhatsApp Engine (/admin/communications/whatsapp) is present in live adminMenuItems");
    assert(menuConfigsContent.includes("key: 'communication'"), "Communication Desk (/admin/communication) is present in live adminMenuItems");
    assert(menuConfigsContent.includes("key: 'monitoring'"), "Monitoring (/admin/monitoring) is present in live adminMenuItems");
    assert(menuConfigsContent.includes("key: 'trash'"), "Trash (/admin/trash) is present in live adminMenuItems");

    // -------------------------------------------------------------
    // TEST 2: Admin Creation and Login History with Stable IDs
    // -------------------------------------------------------------
    console.log("\n[2/10] Verifying Admin Model, Login History & Stable IDs...");
    const testUsername = `gov_admin_${Date.now()}`;
    const testEmail = `gov_admin_${Date.now()}@test.com`;

    testAdmin = await Admin.create({
      username: testUsername,
      email: testEmail,
      password: "TestPassword123!",
      fullName: "Governance Test SuperAdmin",
      role: "super_admin",
      loginHistory: [
        {
          ip: "127.0.0.1",
          location: "Hyderabad, IN",
          device: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
          time: new Date(Date.now() - 3600000),
          status: "SUCCESS",
        },
        {
          ip: "127.0.0.1",
          location: "Hyderabad, IN",
          device: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
          time: new Date(),
          status: "SUCCESS",
        },
      ],
    });

    assert(testAdmin && testAdmin._id, "Admin created with subdocument login history");
    assert(testAdmin.loginHistory.length === 2, "Admin has 2 login history records");
    assert(testAdmin.loginHistory[0]._id, "Login history entries have stable _id generated by Mongoose");

    // -------------------------------------------------------------
    // TEST 3: Login History Safe Removal (Stable ID)
    // -------------------------------------------------------------
    console.log("\n[3/10] Verifying Login History Safe Removal by Stable ID...");
    const { removeLoginHistoryEntry } = require("../controllers/adminController");

    // Try removing historical session (index 0) using its stable _id
    const historicalEntryId = testAdmin.loginHistory[0]._id.toString();
    const mockReq = {
      user: { _id: testAdmin._id },
      userId: testAdmin._id,
      params: { id: historicalEntryId },
    };
    let mockResJson = null;
    let mockResStatus = 200;
    const mockRes = {
      status: (code) => {
        mockResStatus = code;
        return {
          json: (data) => {
            mockResJson = data;
            return data;
          },
        };
      },
      json: (data) => {
        mockResJson = data;
        return data;
      },
    };

    await removeLoginHistoryEntry(mockReq, mockRes);
    assert(mockResStatus === 200 && mockResJson?.success, "Historical login entry removed successfully");

    const updatedAdmin = await Admin.findById(testAdmin._id);
    assert(updatedAdmin.loginHistory.length === 1, "Login history array reduced to 1");

    // Verify AuditLog entry was created for the removal
    const removalAudit = await AuditLog.findOne({
      adminId: testAdmin._id,
      action: "REMOVE_LOGIN_HISTORY_ENTRY",
    });
    assert(Boolean(removalAudit), "Security compliance AuditLog created for login history removal");

    // Try removing the active/most recent session — must be blocked!
    const activeEntryId = updatedAdmin.loginHistory[0]._id.toString();
    let blockResStatus = 200;
    let blockResJson = null;
    const mockBlockRes = {
      status: (code) => {
        blockResStatus = code;
        return {
          json: (data) => {
            blockResJson = data;
            return data;
          },
        };
      },
    };

    await removeLoginHistoryEntry(
      { user: { _id: testAdmin._id }, userId: testAdmin._id, params: { id: activeEntryId } },
      mockBlockRes
    );
    assert(blockResStatus === 400, "Active/Current login session removal is properly prevented (HTTP 400)");

    // -------------------------------------------------------------
    // TEST 4: Profile Update with 2FA Persistence
    // -------------------------------------------------------------
    console.log("\n[4/10] Verifying Profile Update & 2FA Toggle Persistence...");
    const { updateAdminProfile, getAdminProfile } = require("../controllers/adminController");

    let profResJson = null;
    await updateAdminProfile(
      {
        user: { id: testAdmin._id },
        body: {
          fullName: "Updated Governance Admin",
          twoFactorEnabled: true,
        },
      },
      {
        status: () => ({ json: (d) => (profResJson = d) }),
        json: (d) => (profResJson = d),
      }
    );

    assert(profResJson?.success && profResJson?.admin?.twoFactorEnabled === true, "twoFactorEnabled updated to true");
    const freshAdmin = await Admin.findById(testAdmin._id);
    assert(freshAdmin.twoFactorEnabled === true, "twoFactorEnabled persisted in MongoDB Admin document");

    // -------------------------------------------------------------
    // TEST 5: System Settings Security & Persistence
    // -------------------------------------------------------------
    console.log("\n[5/10] Verifying System Settings Security (No Secrets) & Persistence...");
    const { getSystemSettings, updateSystemSettings } = require("../controllers/adminController");

    let settingsGetJson = null;
    await getSystemSettings(
      { user: { _id: testAdmin._id } },
      {
        status: () => ({ json: (d) => (settingsGetJson = d) }),
        json: (d) => (settingsGetJson = d),
      }
    );

    assert(settingsGetJson?.success, "GET /api/admin/settings returned successfully");
    assert(settingsGetJson?.data?.jwtSecret === undefined, "jwtSecret is NOT exposed in settings response");
    assert(settingsGetJson?.data?.smtpPassword === undefined, "smtpPassword is NOT exposed in settings response");
    assert(settingsGetJson?.data?.storageApiKey === undefined, "storageApiKey is NOT exposed in settings response");
    assert(settingsGetJson?.data?.firebaseKey === undefined, "firebaseKey is NOT exposed in settings response");

    // Update settings with safe fields
    let settingsPutJson = null;
    await updateSystemSettings(
      {
        user: { _id: testAdmin._id },
        body: {
          platformName: "HostelMate Enterprise Governance",
          supportEmail: "governance@hostelmate.com",
          currency: "INR",
          billingRate: 2.5,
          maintenanceMode: false,
        },
      },
      {
        status: () => ({ json: (d) => (settingsPutJson = d) }),
        json: (d) => (settingsPutJson = d),
      }
    );

    assert(settingsPutJson?.success, "PUT /api/admin/settings updated successfully");
    assert(settingsPutJson?.data?.platformName === "HostelMate Enterprise Governance", "platformName updated");

    const persistedSettings = await SystemSetting.findOne().lean();
    assert(persistedSettings.platformName === "HostelMate Enterprise Governance", "Settings persisted in MongoDB SystemSetting collection");
    assert(persistedSettings.billingRate === 2.5, "billingRate persisted in MongoDB");

    // -------------------------------------------------------------
    // TEST 6: Backup Metadata Operation
    // -------------------------------------------------------------
    console.log("\n[6/10] Verifying Backup Intent & Metadata Tracking...");
    const { runBackup, getBackups } = require("../controllers/adminController");

    let backupResJson = null;
    await runBackup(
      { user: { _id: testAdmin._id }, userId: testAdmin._id },
      {
        status: () => ({ json: (d) => (backupResJson = d) }),
        json: (d) => (backupResJson = d),
      }
    );

    assert(backupResJson?.success && backupResJson?.backup?.status === "initiated", "runBackup records snapshot intent");

    let backupsListJson = null;
    await getBackups(
      {},
      {
        status: () => ({ json: (d) => (backupsListJson = d) }),
        json: (d) => (backupsListJson = d),
      }
    );
    assert(backupsListJson?.success && Array.isArray(backupsListJson.data), "getBackups returns backup history list");

    // -------------------------------------------------------------
    // TEST 7: Today's Tasks Completed Task Dismissal (AdminTaskDismissal)
    // -------------------------------------------------------------
    console.log("\n[7/10] Verifying Today's Tasks Dismissal (Preserving AuditLog)...");
    const { dismissCompletedTask } = require("../controllers/adminController");
    const { getPendingCommunicationTasks } = require("../controllers/communicationController");

    // Create a sample communication and audit log
    const testComm = await Communication.create({
      type: "whatsapp",
      recipient: "919876543210",
      recipientName: "Test Resident",
      recipientType: "Resident",
      message: "Test completed communication",
      mode: "manual_wame",
      status: "manual_opened",
      openedAt: new Date(),
    });

    const testAudit = await AuditLog.create({
      adminId: testAdmin._id,
      action: "APPROVE_HOSTEL_REGISTRATION",
      actionType: "CREATE",
      entity: "Hostel",
      details: { message: "Test approved registration for task dismissal" },
      timestamp: new Date(),
    });

    // Dismiss the completed communication task
    const commTaskId = `done_wame_${testComm._id}`;
    let dismissJson = null;
    await dismissCompletedTask(
      {
        user: { _id: testAdmin._id, role: "super_admin" },
        userId: testAdmin._id,
        params: { id: commTaskId },
        body: { reason: "Task handled by governance officer" },
      },
      {
        status: () => ({ json: (d) => (dismissJson = d) }),
        json: (d) => (dismissJson = d),
      }
    );

    assert(dismissJson?.success, "dismissCompletedTask executed successfully");

    const dismissalRecord = await AdminTaskDismissal.findOne({
      adminId: testAdmin._id,
      taskId: commTaskId,
    });
    assert(Boolean(dismissalRecord), "AdminTaskDismissal document created in MongoDB");

    // Query Today's Tasks — the dismissed task must be filtered out!
    let tasksResJson = null;
    await getPendingCommunicationTasks(
      {
        user: { _id: testAdmin._id, role: "super_admin" },
        admin: { _id: testAdmin._id, role: "super_admin" },
      },
      {
        status: () => ({ json: (d) => (tasksResJson = d) }),
        json: (d) => (tasksResJson = d),
      }
    );

    assert(tasksResJson?.success, "getPendingCommunicationTasks returned successfully");
    const completedList = tasksResJson?.completedTasksToday || [];
    const isDismissedPresent = completedList.some((t) => t.id === commTaskId || String(t.dbId) === String(testComm._id));
    assert(!isDismissedPresent, "Dismissed task is cleanly excluded from completedTasksToday view");

    // CRITICAL: Ensure underlying Communication and AuditLog records are NOT deleted
    const checkComm = await Communication.findById(testComm._id);
    const checkAudit = await AuditLog.findById(testAudit._id);
    assert(Boolean(checkComm), "CRITICAL: Communication document was NOT deleted (preserved for compliance)");
    assert(Boolean(checkAudit), "CRITICAL: AuditLog document was NOT deleted (preserved in vault)");

    // -------------------------------------------------------------
    // TEST 8: Frontend Components Audit (Dark Theme, Buttons, Form Inputs)
    // -------------------------------------------------------------
    console.log("\n[8/10] Verifying Frontend Components (Dark Theme, Actions, Contrast)...");

    // Drawer Dark Theme
    const drawerPath = path.join(__dirname, "../../Frontend/src/components/MessageDetailDrawer.jsx");
    const drawerContent = fs.readFileSync(drawerPath, "utf8");
    assert(drawerContent.includes("bg-slate-900"), "MessageDetailDrawer uses dark theme background (bg-slate-900)");
    assert(drawerContent.includes("border-slate-800"), "MessageDetailDrawer uses dark theme border (border-slate-800)");
    assert(!drawerContent.includes("bg-white h-full"), "MessageDetailDrawer removed white container background");

    // AdminTasksPage Action Buttons
    const tasksPagePath = path.join(__dirname, "../../Frontend/src/superadmin/views/AdminTasksPage.jsx");
    const tasksPageContent = fs.readFileSync(tasksPagePath, "utf8");
    assert(tasksPageContent.includes("handleDismissTask"), "AdminTasksPage includes handleDismissTask handler");
    assert(tasksPageContent.includes("verify_payment"), "AdminTasksPage includes Verify Payment action");
    assert(tasksPageContent.includes("Removing..."), "AdminTasksPage includes completed tasks Remove button");

    // PlatformSettings Secret Hiding
    const settingsViewPath = path.join(__dirname, "../../Frontend/src/superadmin/views/PlatformSettings.jsx");
    const settingsViewContent = fs.readFileSync(settingsViewPath, "utf8");
    assert(!settingsViewContent.includes('name="jwtSecret"'), "PlatformSettings does not contain jwtSecret input field");
    assert(!settingsViewContent.includes('name="firebaseKey"'), "PlatformSettings does not contain firebaseKey input field");
    assert(settingsViewContent.includes("handleRunBackup"), "PlatformSettings includes backup execution handler");

    // AdminProfile Login History Action
    const profileViewPath = path.join(__dirname, "../../Frontend/src/superadmin/views/AdminProfile.jsx");
    const profileViewContent = fs.readFileSync(profileViewPath, "utf8");
    assert(profileViewContent.includes("handleRemoveLoginHistory"), "AdminProfile includes handleRemoveLoginHistory");
    assert(profileViewContent.includes("Current Session"), "AdminProfile marks current session distinct from removable history");

    // -------------------------------------------------------------
    // TEST 9: Cleanup Test Records
    // -------------------------------------------------------------
    console.log("\n[9/10] Cleaning up temporary test fixtures...");
    await Admin.deleteOne({ _id: testAdmin._id });
    await Communication.deleteOne({ _id: testComm._id });
    await AuditLog.deleteMany({ adminId: testAdmin._id });
    await AdminTaskDismissal.deleteMany({ adminId: testAdmin._id });
    assert(true, "Test records cleaned up cleanly");

    // -------------------------------------------------------------
    // TEST 10: Final Summary
    // -------------------------------------------------------------
    console.log("\n[10/10] Final Assessment:");
    console.log(`  Total Passed: ${passed}`);
    console.log(`  Total Failed: ${failed}`);

    if (failed === 0) {
      console.log("\n=======================================================");
      console.log("  ✓ ALL SUPERADMIN GOVERNANCE TESTS PASSED (100% GREEN)");
      console.log("=======================================================\n");
    } else {
      console.error(`\n  ✗ ${failed} test(s) failed.`);
      process.exit(1);
    }
  } catch (err) {
    console.error("Test execution error:", err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
  }
}

runTests();
